### ISSUE TITLE
Problems building w/ JSAPI 3.13 

### ISSUE THREAD

**Issue by tomwayson** [steveoh/grunt-esri-slurp#34]
Tried to update my example repo to 3.13 over the weekend, and I got the error below when running the build. Also looks like @tsamaya [had the same issue](https://github.com/Esri/dojo-bootstrap-map-js/issues/83#issuecomment-82650007) in the Dojo Bootstrap map repo, which uses a similar build profile to my example repo.

Briefly looking into geometery_ROOT.js, it seems like the bundles are inlined in the file, but I didn't have much time to get beyond that. I won't have time to look into this until maybe next week, just wanted to give you a heads up and see if you guys have seen this on your boilerplate?

```
error(354) Root bundle indicates localized bundles that don't exist.
	Root: esri/nls/geometry_ROOT; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_ar; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_ca; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_cs; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_da; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_de; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_el; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_en-gb; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_en-us; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_es-es; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_fi-fi; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_fr-fr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_he-il; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_hu; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_it-it; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_ja-jp; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_ko-kr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_nb; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_nl-nl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_pl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_pt-br; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_pt-pt; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_ru; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_sk; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_sl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_sv; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_th; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_tr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_zh-cn; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/geometry_zh-tw; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number'.
	Root: esri/nls/renderer_ROOT; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_ar; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_ca; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_cs; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_da; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_de; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_el; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_en-gb; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_en-us; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_es-es; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_fi-fi; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_fr-fr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_he-il; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_hu; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_it-it; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_ja-jp; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_ko-kr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_nb; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_nl-nl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_pl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_pt-br; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_pt-pt; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_ru; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_sk; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_sl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_sv; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_th; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_tr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_zh-cn; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/renderer_zh-tw; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_ROOT; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_ar; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_ca; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_cs; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_da; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_de; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_el; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_en-gb; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_en-us; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_es-es; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_fi-fi; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_fr-fr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_he-il; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_hu; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_it-it; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_ja-jp; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_ko-kr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_nb; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_nl-nl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_pl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_pt-br; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_pt-pt; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_ru; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_sk; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_sl; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_sv; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_th; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_tr; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_zh-cn; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
	Root: esri/nls/symbol_zh-tw; missing bundles: 'dojo/cldr/nls/gregorian','dojo/cldr/nls/number','esri/nls/jsapi'.
```

**Comment by steveoh** [comment]
yes, some of the problems seem to stem from esri codes. @stdavis was going to make an issue showing what he spent all of yesterday looking into. He showed me paths that don't resolve, improperly cased AMD imports causing issues, etc. Hopefully we can figure this out soon.

**Comment by tsamaya** [comment]
That's it ! Thanks Tom. I actually have the same "missing bundles" issue.

**Comment by steveoh** [comment]
The bundle files _are_ there though. Not quite sure what is going on.

**Comment by stdavis** [comment]
I think that it has to do with the i18n files being already run through the build system. I was going to wait until we can download a fresh copy of the 3.13 api to see whats up. 

-Scott

**Comment by steveoh** [comment]
i just pushed the `3.13` modules from the sdk pages. But I'm not going to try the build until later. Update your modules and give it a shot.

**Comment by stdavis** [comment]
That took care of the i18n bundle problem. The bad path in
`esri/themes/calcite/dijit/document.css` is still an issue. I propose that
we just remove that file from the module list since I can't find anywhere
where it's actually used.

On Wed, Mar 18, 2015 at 7:36 PM, steveoh <notifications@github.com> wrote:

> i just pushed the 3.13 modules from the sdk pages. But I'm not going to
> try the build until later. Update your modules and give it a shot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steveoh/grunt-esri-slurp/issues/34#issuecomment-83251964>
> .
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by tsamaya** [comment]
I made it work with esri-slurp-example from @tomwayson but I still have the
missing bundle message on the dojo-bootstrapmap-js repo.I may miss
something. I will clean my workspace and do it again tomorrow.

2015-03-19 14:43 GMT+01:00 Scott Davis <notifications@github.com>:

> That took care of the i18n bundle problem. The bad path in
> `esri/themes/calcite/dijit/document.css` is still an issue. I propose that
> we just remove that file from the module list since I can't find anywhere
> where it's actually used.
>
>

**Comment by stdavis** [comment]
Ya, grunt-esri-slurp doesn't clean up from older esri versions, it just
overwrites existing files. So you'll want to delete the esri folder
manually.

On Thu, Mar 19, 2015 at 10:51 AM, Arnaud Ferrand <notifications@github.com>
wrote:

> I made it work with esri-slurp-example from @tomwayson but I still have the
> missing bundle message on the dojo-bootstrapmap-js repo.I may miss
> something. I will clean my workspace and do it again tomorrow.
>
> 2015-03-19 14:43 GMT+01:00 Scott Davis <notifications@github.com>:
>
> > That took care of the i18n bundle problem. The bad path in
> > `esri/themes/calcite/dijit/document.css` is still an issue. I propose
> that
> > we just remove that file from the module list since I can't find anywhere
> > where it's actually used.
> >
> >
> > On Wed, Mar 18, 2015 at 7:36 PM, steveoh <notifications@github.com>
> wrote:
> >
> > > i just pushed the 3.13 modules from the sdk pages. But I'm not going to
> > > try the build until later. Update your modules and give it a shot.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/steveoh/grunt-esri-slurp/issues/34#issuecomment-83251964
> > >
> > > .
> > >
> >
> >
> >
> > --
> > *Scott Davis*
> > Utah AGRC <http://gis.utah.gov/developer/>
> > stdavis@utah.gov
> > @ScottAGRC <https://twitter.com/ScottAGRC>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/steveoh/grunt-esri-slurp/issues/34#issuecomment-83586484
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steveoh/grunt-esri-slurp/issues/34#issuecomment-83659890>
> .
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by steveoh** [comment]
I just updated the slurps. scott do you want to test it with your build?

**Comment by stdavis** [comment]
Tested and working for me with 1.4.3.

On Thu, Mar 19, 2015 at 11:03 AM, steveoh <notifications@github.com> wrote:

> I just updated the slurps. scott do you want to test it with your build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steveoh/grunt-esri-slurp/issues/34#issuecomment-83666285>
> .
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by tomwayson** [comment]
Nice work @stdavis and @steveoh!
